methods:
     1:
       algorithm: "cma_esr_csa"
     2:
       algorithm: "cma_esr_ppmf"
     3:
       algorithm: "des_cma_esr_ppmf"
     4:
       algorithm: "des_cma_esr_csa"

ids:
  - "csa-cec22"
  - "ppmf-cec22"
  - "des-cma-ppmf-cec22"
  - "des-cma-csa-cec22"
probnum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
dims:
  - 10
cec: 22
repnum: 30
suite: "bias_shift_rot"
cpupc: 0.25
source: "~/gecco2022/R"
dest: "~/gecco2022/data/"
